# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 乐水榭
email: vonfry314@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  论极语易个人博客——乐水榭，一个太极／易经爱好者，一个程序员，一个vim+emacs粉，一个hacker。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vonfry.name" # the base hostname & protocol for your site, e.g. http://example.com
excerpt_separator: "<!-- more -->"

# User settings
username: Vonfry
user_description: 论极语易-Vonfry
user_title: vonfry
email: mail@vonfry.name
twitter_username: Vonfry314
github_username:  VonFry

# Build settings
destination:  ./_site
markdown: kramdown
theme: jekyll-theme-so-simple

sass:
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false
keep_files:
  - .git
  - .gitignore
  - theme
  - _drafts
include:
  - .htaccess
exclude:
  - package.json
  - src
  - node_modules
  - Gemfile
  - Gemfile.lock
  - readme.org
  - vendor
  - _sites

# Conversion
highlighter: rouge

# Outputting
permalink: /:slug/
timezone: Asia/Shanghai
encoding: utf-8

quiet: false
verbose: false
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Vonfry"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Vonfry"
      toc: true
liquid:
  error_mode: warn

# Plugins
safe: No
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 16
  permalink: '/page/:num/'
  title: ':title - # :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2
  extension: html
  indexpage: 'index'

# Theme config
mathjax: true.
search_full_content: true
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"
