# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 乐水榭 | 论极语易-Vonfry 博客
description: > # this means to ignore newlines until "baseurl:"
  Just for fun.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vonfry.name" # the base hostname & protocol for your site, e.g. http://example.com
excerpt_separator: "<!-- more -->"
locale: "zh-CN"

# User settings
username: Vonfry
user_description: 论极语易-Vonfry
user_title: vonfry
email: mail@vonfry.name

# Build settings
destination:  ./_site
markdown: kramdown
theme: jekyll-theme-so-simple

sass:
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false
include:
  - .htaccess
exclude:
  - Gemfile
  - Gemfile.lock
  - readme.org
  - vendor
  - _sites
  - .git
  - .gitignore
  - _drafts

# Conversion
highlighter: rouge

# Outputting
permalink: /:slug/
timezone: "Asia/Shanghai"
encoding: "UTF-8"

quiet: false
verbose: false
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Vonfry"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Vonfry"
liquid:
  error_mode: warn

# Plugins
safe: false
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 8
paginate_path: /page:num/

# Theme config
mathjax: true.
search_full_content: true
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"
footer_links:
  - title: Twitter
    url: https://twitter.com/Vonfry314
    icon: fab fa-twitter-square
  - title: GitLab
    url: https://gitlab.com/Vonfry
    icon: fab fa-gitlab
  - title: GitHub
    url: https://github.com/Vonfry
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
copyright: "This site is made with <3 by *me, myself, and I*."
logo: static/images/default/logo.jpg
