title: 乐水榭 | 论极语易-Vonfry 博客
description: >
  Just for fun.<br/>
  不会记录非常复杂的东西（那种东西在脑子里，也懒得写成博客）。<br/>
  主要用于记录开发中的小问题和一些理解。
baseurl: ""
url: "https://vonfry.name"
excerpt_separator: "<!-- more -->"
locale: "zh-CN"

# User settings
username: Vonfry
user_description: 论极语易-Vonfry
user_title: vonfry
email: mail@vonfry.name

# Build settings
destination:  ./_site
markdown: kramdown
theme: jekyll-theme-so-simple

sass:
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false
include:
  - .htaccess
exclude:
  - Gemfile
  - Gemfile.lock
  - readme.org
  - vendor
  - _sites
  - .git
  - .gitignore
  - _drafts

# Conversion
highlighter: rouge

# Outputting
permalink: /:slug/
timezone: "Asia/Shanghai"
encoding: "UTF-8"

quiet: false
verbose: false
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Vonfry"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Vonfry"
liquid:
  error_mode: warn

# Plugins
safe: false
plugins:
  - jekyll-paginate
  - jekyll-last-modified-at

# Plugin: last modified
last-modified-at:
    date-format: "%B %d, %Y"

paginate: 8
paginate_path: /page:num/

# Theme config
mathjax: true.
search_full_content: true
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"
footer_links:
  - title: Twitter
    url: https://twitter.com/Vonfry314
    icon: fab fa-twitter-square
  - title: GitLab
    url: https://gitlab.com/Vonfry
    icon: fab fa-gitlab
  - title: GitHub
    url: https://github.com/Vonfry
    icon: fab fa-github-square
  - title: Feed
    url: feed.xml
    icon: fas fa-rss-square
copyright: "This site is made with <3 by *me, myself, and I*."
logo: static/images/default/logo.jpg
date_format: "%B %d, %Y"
