baseURL: https://vonfry.name
disablePathToLower: true
languageCode: en-us
title: 乐水榭 | 论极语易-Vonfry 博客
theme: hugo-coder
defaultcontentlanguage: "en"

paginate: 20

pygmentsstyle: "solarized-dark"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true

taxonomies:
  category: "categories"
  series: "series"
  tag: "tags"

params:
  author: "Vonfry | 论极语易"
  info: "Code for Fun."
  description: "乐水榭 | Vonfry's personal website"
  keywords: "blog,developer,personal"
  avatarurl: "/images/default/logo-white.png"
  gravatar: "mail@vonfry.name"

  since: 2015

  favicon_32: "/images/default/logo-white.png"
  favicon_16: "/images/default/logo-white.png"

  enableTwemoji: true
  hidecolorschemetoggle: true
  colorScheme: "dark"

  social:
  - name: "Repos"
    icon: "fa fa-code-fork fa-2x"
    weight: 1
    url: "https://git.sr.ht/~vonfry"
  - name: "Github"
    icon: "fa fa-github fa-2x"
    weight: 1
    url: "https://github.com/Vonfry/"
  - name: "Gitlab"
    icon: "fa fa-gitlab fa-2x"
    weight: 2
    url: "https://gitlab.com/Vonfry/"
  - name: "Twitter"
    icon: "fa fa-twitter fa-2x"
    weight: 3
    url: "https://twitter.com/Vonfry314/"

menu:
  main:
  - name: "Posts"
    weight: 1
    url: "posts/"
  - name: "Categories"
    weight: 2
    url: "categories/"
  - name: "Tags"
    weight: 2
    url: "tags/"
  - name: "About"
    weight: 3
    url: "about/"
